#include "LanguageManager.h"

void LanguageManager::setJapanese(){
    strArray.clear();
    strArray.push_back(std::string("")); // 0
    strArray.push_back(std::string("")); // 1
    strArray.push_back(std::string("")); // 2
    strArray.push_back(std::string("")); // 3
    strArray.push_back(std::string("")); // 4
    strArray.push_back(std::string("")); // 5
    strArray.push_back(std::string("")); // 6
    strArray.push_back(std::string("")); // 7
    strArray.push_back(std::string("")); // 8
    strArray.push_back(std::string("")); // 9
    strArray.push_back(std::string("")); // 10
    strArray.push_back(std::string("")); // 11
    strArray.push_back(std::string("")); // 12
    strArray.push_back(std::string("")); // 13
    strArray.push_back(std::string("")); // 14
    strArray.push_back(std::string("")); // 15
    strArray.push_back(std::string("")); // 16
    strArray.push_back(std::string("")); // 17
    strArray.push_back(std::string("")); // 18
    strArray.push_back(std::string("")); // 19
    strArray.push_back(std::string("")); // 20
    strArray.push_back(std::string("")); // 21
    strArray.push_back(std::string("")); // 22
    strArray.push_back(std::string("")); // 23
    strArray.push_back(std::string("")); // 24
    strArray.push_back(std::string("")); // 25
    strArray.push_back(std::string("")); // 26
    strArray.push_back(std::string("")); // 27
    strArray.push_back(std::string("")); // 28
    strArray.push_back(std::string("")); // 29
    strArray.push_back(std::string("")); // 30
    strArray.push_back(std::string("")); // 31
    strArray.push_back(std::string("")); // 32
    strArray.push_back(std::string("")); // 33
    strArray.push_back(std::string("")); // 34
    strArray.push_back(std::string("")); // 35
    strArray.push_back(std::string("")); // 36
    strArray.push_back(std::string("")); // 37
    strArray.push_back(std::string("")); // 38
    strArray.push_back(std::string("")); // 39
    strArray.push_back(std::string("")); // 40
    strArray.push_back(std::string("")); // 41
    strArray.push_back(std::string("")); // 42
    strArray.push_back(std::string("")); // 43
    strArray.push_back(std::string("")); // 44
    strArray.push_back(std::string("")); // 45
    strArray.push_back(std::string("")); // 46
    strArray.push_back(std::string("")); // 47
    strArray.push_back(std::string("")); // 48
    strArray.push_back(std::string("")); // 49
    strArray.push_back(std::string("")); // 50
    strArray.push_back(std::string("")); // 51
    strArray.push_back(std::string("")); // 52
    strArray.push_back(std::string("")); // 53
    strArray.push_back(std::string("")); // 54
    strArray.push_back(std::string("")); // 55
    strArray.push_back(std::string("")); // 56
    strArray.push_back(std::string("")); // 57
    strArray.push_back(std::string("")); // 58
}